services:

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-server
      - app-server
      - frontend
    networks:
      - dev-net

  auth-server:
    build:
      context: ./backend/auth-server
      dockerfile: Dockerfile
    container_name: auth-service
    platform: linux/amd64
    depends_on:
      - postgres-auth
    networks:
      - dev-net
      - postgres-auth

  app-server:
    build:
      context: ./backend/app-server
      dockerfile: Dockerfile
    container_name: app-service
    platform: linux/amd64
    depends_on:
      - postgres-app
      - minio
      - redis
    networks:
      - dev-net
      - minio-net
      - redis-net
      - postgres-app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dev-net

  postgres-auth:
    image: postgres
    container_name: pg-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres-auth

  postgres-app:
    image: postgres
    container_name: pg-app
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-app

  redis:
    image: redis
    container_name: redis
    networks:
      - redis-net

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_DEFAULT_BUCKETS: "my-bucket"
    command: server /data
    networks:
      - minio-net

networks:
  dev-net:
    driver: bridge

  postgres-app:
    driver: bridge

  postgres-auth:
    driver: bridge

  redis-net:
    driver: bridge

  minio-net:
    driver: bridge