spring.application.name=auth-server

spring.datasource.url=jdbc:postgresql://pg-auth:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.security.jwt.private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSBerOh5Xw0VDY25EcVx1ywpwWiduLJZ4uktAmh5upiS8PG2NdxFsTDuXeZVomtz2lZxhoAlIYMIssVn1NIVtOlHret6yxvXfJBkd03qALKz6u3jysYH62dmJiEMoifshthvGz0CULFOWJbSPHJVyyfGvonWKIV7LrWkGgYIa5pSkhqiGZztsEf2IoaTn881zRxvolxJukJcse7IDcYXM7XmVW65/DIHxMR3VxGbzY38yXsOaFFlGzBTHaGnzQ/ddDqTVOgTJG9593ozLy55Ke0OK0OGhPVqSBYuTlt8xC9D7h30eoC3fDEEF14plDQISO/m6f8nIdYk9iFYxENQLjAgMBAAECggEAa1dONGQXJN+5vrApC9w+GY5Vj3vnl3IfxbzGpowpMYdWwJQxh0xAZtIcyE9Y5fztpBkVJ+AM2RtWM1Gg6oIKzMj5SZ9bo4zT8UJcZN0CaTNw8LsNfumwPBDqYYxWCuWIEHuSUcxAbtT9pvhDxLECY3JzIJwRQoi1Ta0bcPmEEBLl2xvke6EpC3mRD3iXSH27anqSlllDYCLsw3s/u+h5ncsa0LGnw7gJZN/C9uGVWVNfGTwY/xv4hje+EqMQtNXD7Q4I/S5NynrvnbjCIkSJFIslJUYIf6zFC7CPaKt37ISQn/M8j/RaqlZV8LZ371Cr7X/7/QcFDAI5X5IvMl3fgQKBgQDxOcQmYqf2yWNBxTC6UbJDjVTm2/CO/aISgkDkB0VCyvilCk15n+9HGxKFbJ0Vo3Ve0SqSfO4yEe9xlK327YfJWC+rgOCcmEatpDz4EiToVEFnAwGTBgAWip6d5s7wMwqU0Y5xEOhYc1k7DSUlgf2xHwOA3V4hSYNy/UH26qtsTQKBgQCa93Kxt4Eo3HeLCql03Y93xIqTwEkSjVCN+21GU9VsAYEVFpATUbM4nAe/3Cmbau7ZAXhfc0Ht9wpV2qF5Q2qHp99G6qp5UtJN8XPVjwTr9vY5CHjSXYuVOxgiePFbzqKENIOzHpJb8FC+GnRJo3UvGbR6/y8LQ4zfGuGeVn4D7wKBgQDCvNqwDlcAcOXzU6iZ0Zgy1qbi1E2ocfNkM8kFDSWJ3WfLfLy84jN92Moj8mIB9Pqst/lBVx/IRhhiPiAOxwUms02Qi7NIV9o/FeaucZ9f+5zs901PDroFeJTCbnFDEkGJkH8IohigR0aS2HLTi9RtJ9dhMdRq1PkMXI3jMuF+xQKBgF3lnYttY0d8/rozBaaYMTwizMzl7+Db23mMZRP97A17g9lhSH9MO8oLUO7B2jwfuQWoTGWZktM7ovmOddTiMoRsBXAU9KJ6uo8bxFIcTKEljN/V8E+W+uK7Yc5Rdf1o4TQ2Fa7M0WX/4QyvPtL3xiN58c+tG7Y5gfwVb6vfQI/lAoGBAKA/j0Y/GyA3K6xoQpAzX49NuIKbjwGkWDzjJvB1Z/jtH7DgmVwEjbJ+fWoxyH3GakPK1eN3OOEFdgTOqQJRJpZRzgZ/HD63RbknwCeK2I3dwSOiIccMLfnmCTBcJdMhUk7TBPaS3R/qWUBfV+646pbPi4EQtd6Nn3yfHqslBH60
app.security.jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkgXqzoeV8NFQ2NuRHFcdcsKcFonbiyWeLpLQJoebqYkvDxtjXcRbEw7l3mVaJrc9pWcYaAJSGDCLLFZ9TSFbTpR63ressb13yQZHdN6gCys+rt48rGB+tnZiYhDKIn7IbYbxs9AlCxTliW0jxyVcsnxr6J1iiFey61pBoGCGuaUpIaohmc7bBH9iKGk5/PNc0cb6JcSbpCXLHuyA3GFzO15lVuufwyB8TEd1cRm82N/Ml7DmhRZRswUx2hp80P3XQ6k1ToEyRvefd6My8ueSntDitDhoT1akgWLk5bfMQvQ+4d9HqAt3wxBBdeKZQ0CEjv5un/JyHWJPYhWMRDUC4wIDAQAB
app.security.access-token-expiration-minutes=15
app.security.refresh-token-expiration-days=7
app.security.issuer=auth-service

app.cookies.access-token.name=acces_token
app.cookies.access-token.http-only=true
app.cookies.access-token.secure=false
app.cookies.access-token.max-age=900
app.cookies.access-token.path=/
app.cookies.access-token.same-site=strict

app.cookies.refresh-token.name=refresh-token
app.cookies.refresh-token.http-only=true
app.cookies.refresh-token.secure=false
app.cookies.refresh-token.max-age=604800
app.cookies.refresh-token.path=/api/auth/refresh
app.cookies.refresh-token.same-site=strict

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG