spring.application.name=app-server

spring.datasource.url=jdbc:postgresql://postgres-app:5432/appdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.time-zone=UTC

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0

app.minio.endpoint=http://minio:9000
app.minio.access-key=minioadmin
app.minio.secret-key=minioadmin
app.minio.bucket-name=posts
app.minio.secure=false
app.minio.public-access=true

app.cache.post.ttl-minutes=30
app.cache.top-users-limit=10

app.auth-service.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkgXqzoeV8NFQ2NuRHFcdcsKcFonbiyWeLpLQJoebqYkvDxtjXcRbEw7l3mVaJrc9pWcYaAJSGDCLLFZ9TSFbTpR63ressb13yQZHdN6gCys+rt48rGB+tnZiYhDKIn7IbYbxs9AlCxTliW0jxyVcsnxr6J1iiFey61pBoGCGuaUpIaohmc7bBH9iKGk5/PNc0cb6JcSbpCXLHuyA3GFzO15lVuufwyB8TEd1cRm82N/Ml7DmhRZRswUx2hp80P3XQ6k1ToEyRvefd6My8ueSntDitDhoT1akgWLk5bfMQvQ+4d9HqAt3wxBBdeKZQ0CEjv5un/JyHWJPYhWMRDUC4wIDAQAB
app.auth-service.issuer=auth-service

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.ru.bolvanchiki.security.JwtAuthFilter=DEBUG